export const ONBOARDING_STEPS = [
  // Day 1
  {
    id: 'schedule-1on1',
    label: 'Join Slack',
    icon: '💬',
    category: 'Admin & Setup',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'slack-phone',
    label: 'Slack on phone',
    icon: '📱',
    category: 'Communication',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'company-rules',
    label: 'Company rules',
    icon: '📜',
    category: 'Company & Culture',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'explore-aura-library',
    label: 'Aura Library',
    icon: '✨',
    category: 'Product',
    day: 1,
    badge: 'Monday–Friday',
  },
  {
    id: 'social-media',
    label: 'Follow socials',
    icon: '📣',
    category: 'External Presence',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'linear-access',
    label: 'Linear & Mixpanel',
    icon: '📊',
    category: 'Admin & Setup',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'avenger-profile',
    label: 'Avenger profile',
    icon: '🦸',
    category: 'Product',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'producthunt',
    label: 'Product Hunt',
    icon: '🚀',
    category: 'External Presence',
    day: 1,
    badge: '5 min',
  },
  // Day 3
  {
    id: 'review-landing-page',
    label: 'Kahana site',
    icon: '🌐',
    category: 'Company & Culture',
    day: 3,
    badge: '15 min',
  },
  // Optional
  {
    id: 'duolingo-article',
    label: 'Growth framework',
    icon: '📈',
    category: 'Company & Culture',
    day: 'optional',
    badge: 'optional',
  },
  // Day 5
  {
    id: 'tools-access',
    label: 'Role tools',
    icon: '🔑',
    category: 'Admin & Setup',
    day: 5,
    badge: '5 min',
  },
  {
    id: 'time-log',
    label: 'Weekly Time Log',
    icon: '🗓️',
    category: 'Admin & Setup',
    day: 5,
    badge: 'weekly',
  },
  {
    id: 'onboarding-survey',
    label: 'Onboarding survey',
    icon: '📝',
    category: 'Wrap-up',
    day: 5,
    badge: null,
  },
  // Coming soon
  {
    id: 'soc2-compliance',
    label: 'SOC 2 policies',
    icon: '🔒',
    category: 'Company & Culture',
    comingSoon: true,
  },
]
