export const ONBOARDING_STEPS = [
  // Day 1 — get set up
  {
    id: 'company-rules',
    label: 'Read Company Rules',
    icon: 'book',
    category: 'Company & Culture',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'schedule-1on1',
    label: 'Join Slack',
    icon: 'message',
    category: 'Admin & Setup',
    day: 1,
    badge: '10 min',
  },
  {
    id: 'weekly-1on1',
    label: 'Schedule weekly 1-on-1 with Adam',
    icon: 'meeting',
    category: 'Admin & Setup',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'social-media',
    label: 'Follow Kahana & Adam on socials',
    icon: 'megaphone',
    category: 'External Presence',
    day: 1,
    badge: '5 min',
  },
  {
    id: 'tools-access',
    label: 'Request tools access',
    icon: 'key',
    category: 'Admin & Setup',
    day: 1,
    badge: '10 min',
  },
  {
    id: 'create-profiles',
    label: 'Create your profiles',
    icon: 'user',
    category: 'Product',
    day: 1,
    badge: '15 min',
  },
  {
    id: 'review-landing-page',
    label: 'Review Kahana website',
    icon: 'globe',
    category: 'Company & Culture',
    day: 1,
    badge: '15 min',
  },
  {
    id: 'explore-aura-library',
    label: 'Explore Aura Library',
    icon: 'sparkles',
    category: 'Product',
    day: 1,
    badge: 'Monday–Friday',
  },
  {
    id: 'time-log',
    label: 'Complete Time Log every Friday',
    icon: 'calendar',
    category: 'Admin & Setup',
    day: 1,
    badge: 'every Friday',
  },
  {
    id: 'onboarding-survey',
    label: 'Complete Onboarding Survey',
    icon: 'clipboard',
    category: 'Wrap-up',
    day: 1,
    badge: '5 min',
  },
  // Day 2 — lay of the land
  {
    id: 'market-map',
    label: 'Explore the Market Map',
    icon: 'map',
    category: 'Company & Culture',
    day: 2,
    badge: '15 min',
  },
  {
    id: 'company-landscape',
    label: 'Browse Company Landscape',
    icon: 'book',
    category: 'Company & Culture',
    day: 2,
    badge: '20 min',
  },
  {
    id: 'how-we-work',
    label: 'Read How We Work (Linear, Slack, Mixpanel)',
    icon: 'key',
    category: 'Admin & Setup',
    day: 2,
    badge: '15 min',
  },
  {
    id: 'sops',
    label: 'Read SOPs (Book & Video Clubs)',
    icon: 'book',
    category: 'Product',
    day: 2,
    badge: '15 min',
  },
  {
    id: 'project-charter',
    label: 'Read the Project Charter',
    icon: 'clipboard',
    category: 'Company & Culture',
    day: 2,
    badge: '30–45 min',
  },
  // Optional
  {
    id: 'duolingo-article',
    label: 'Learn the Growth Framework',
    icon: 'trend',
    category: 'Company & Culture',
    day: 'optional',
    badge: 'optional',
  },
  // Coming soon
  {
    id: 'soc2-compliance',
    label: 'Review SOC 2 Policies',
    icon: 'lock',
    category: 'Company & Culture',
    comingSoon: true,
  },
]
